import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <Link href={"/CSR"}>CSR렌더링</Link>
        <Link href={"/ISR"}>ISR렌더링</Link>
        <Link href={"/SSG"}>SSG렌더링</Link>
        <Link href={"/SSR"}>SSR렌더링</Link>
      </header>
      <body>{children}</body>
    </html>
  );
}
